var NewToDoTmpl = [
    '<div id="NewEntryModalID" class="modal hide fade">',
    '<div class="modal-header">',
        '<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>',
        '<h3 class="text-info">Add new ToDo :)</h3>',
    '</div>',
    '<div class="modal-body">',
        '<form action="" id="newEntry">',
            '<fieldset>',
                '<label for="NameID">',
                    'Name of Event',
                    '<input type="text" id="NameID" placeholder="<%= nameInput%>"/>',
                '</label>',
                '<label for="EntryDateID" class="half_width">',
                    'Date of Event',
                    '<div class="input-append date">',
                        '<input class="span2 no-need-clear" size="16" id="EntryDateID" type="text" value="<%= date%>" data-date="12-02-2012" data-date-format="dd-mm-yyyy">',
                        '<span class="add-on"><i class="icon-calendar"></i></span>',
                    '</div>',
                '</label>',
                '<div class="time-holder half_width">',
                    '<div class="numbers">',
                        '<div class="numbers-label">Hours</div>',
                        '<div class="numbers_nav time_up">\&#9652;</div>',
                        '<div class="numbers_container hour" data-date-format="hour" data-date-shorthand="HH">',
                            '<div class="numbers_inner_container">',
                                '<div class="number"><%= moment(""+hour, "hh").add("h", -2).format("HH") %></div>',
                                '<div class="number"><%=  moment(""+hour, "hh").add("h", -1).format("HH") %></div>',
                                '<div class="number current"><%= hour%></div>',
                                '<div class="number"><%=  moment(""+hour, "hh").add("h", 1).format("HH")%></div>',
                                '<div class="number"><%=  moment(""+hour, "hh").add("h", 2).format("HH")%></div>',
                            '</div>',
                        '</div>',
                        '<div class="numbers_nav time_down">\&#9662;</div>',
                    '</div>',
                    '<div class="numbers">',
                        '<div class="numbers-label">Minutes</div>',
                        '<div class="numbers_nav time_up">\&#9652;</div>',
                        '<div class="numbers_container minute" data-date-format="minute" data-date-shorthand="mm">',
                            '<div class="numbers_inner_container">',
                                '<span class="number"><%= moment(""+minute, "mm").add("m", -2).format("mm")%></span>',
                                '<span class="number"><%= moment(""+minute, "mm").add("m", -1).format("mm")%></span>',
                                '<span class="number current"><%= minute%></span>',
                                '<span class="number"><%= moment(""+minute, "mm").add("m", 1).format("mm")%></span>',
                                '<span class="number"><%= moment(""+minute, "mm").add("m", 2).format("mm")%></span>',
                            '</div>',
                        '</div>',
                        '<div class="numbers_nav time_down">\&#9662;</div>',
                    '</div>',
                '</div>',
            '</fieldset>',
        '</form>',
        '<span class="error-message"></span>',
    '</div>',
    '<div class="modal-footer">',
        '<a href="#" id="CancelNewEntry" class="btn btn-info">Cancel</a>',
        '<a href="#" id="SaveNewEntry" class="btn btn-success ">Save</a>',
    '</div>',
'</div>'
]